### ISSUE TITLE
Global variable getting override while using loop

### ISSUE THREAD

**Issue by ratheeshart** [aaswtest/newman-reporter-junitxray#3]
`
        global = xml.create("testsuites", { version: "1.0", encoding: "UTF-8" });
        global.att("name", collection.name);
`

Issue:
 I need to run multiple collection using newman. On each collection the reports were generated at the same time the `global` gets overrided with xml. This cause the next collection fail at newman SecureFS class.

**Comment by ratheeshart** [comment]
#5

**Comment by aaswtest** [comment]
published version 1.0.3 to npm that includes this change
